from exceptions.auth import AuthError

__all__ = ["AuthError"]
